### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by M4ZZ3-Real** [aeziotech/discord-invite-logger#4]
I have this error ? 

(node:25) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'emojis' of undefined
at /home/container/src/handler/emojis.js:9:45
at Array.forEach (<anonymous>)
at Client.<anonymous> (/home/container/src/handler/emojis.js:8:39)
at Client.emit (events.js:327:22)
at WebSocketManager.triggerClientReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:431:17)
at WebSocketManager.checkShardsReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:415:10)
at WebSocketShard.<anonymous> (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:197:14)
at WebSocketShard.emit (events.js:315:20)
at WebSocketShard.checkReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:475:12)
at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:447:16)

**Comment by aeziotech** [comment]
Hello. The bot is now up to date, using discord.js v13, with button systems.
